### ISSUE TITLE
Beam seems to mangle unicode characters during query generation

### ISSUE THREAD

**Issue by saevarb** [tathougies/beam#138] opened 2018-02-12 09:29 UTC
Trying to insert unicode characters into the database via beam seems to mangle them during query generation.

Sample code:

```haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE AllowAmbiguousTypes #-}

module Bug where

import Data.Text(Text)

import Database.Beam
import Database.Beam.Postgres (connectPostgreSQL, Postgres)

data SimpleTable f
  = SimpleTable
  { simpletblField1 :: Columnar f (Auto Int)
  , simpletblField2 :: Columnar f Text
  }
  deriving Generic
instance Beamable SimpleTable

instance Table SimpleTable where
  data PrimaryKey SimpleTable f = SimpleTableId (Columnar f (Auto Int)) deriving Generic
  primaryKey = SimpleTableId <$> simpletblField1
instance Beamable (PrimaryKey SimpleTable)

data MyDb f =
  MyDb { mydbSimpleTable :: f (TableEntity SimpleTable) } deriving Generic
instance Database MyDb


myDb :: DatabaseSettings Postgres MyDb
myDb = defaultDbSettings

test :: IO ()
test = do
    -- create a database named test
    -- table creation not necessary to see debug output
    conn <- connectPostgreSQL "dbname='test'"
    withDatabaseDebug putStrLn conn $
        runInsert $ insert (mydbSimpleTable myDb) $ insertValues [SimpleTable (Auto Nothing) "æææþþþþððð"]
````

Expected output:

```
INSERT INTO "simple_table"("field1", "field2") VALUES (DEFAULT, 'æææþþþþððð')
```

Actual output:

```
INSERT INTO "simple_table"("field1", "field2") VALUES (DEFAULT, 'Ã¦Ã¦Ã¦Ã¾Ã¾Ã¾Ã¾Ã°Ã°Ã°')
```

**Comment by 3noch** [comment] 2018-02-12 15:26
I think I've seen this as well.

**Comment by tathougies** [comment] 2018-02-12 22:54
Oh wow... that's really too bad. I'll take a look immediately.

**Comment by mulderr** [comment] 2018-02-12 23:59
> Is this only in postgres?

Looks to be. I can reproduce with postgres but not with sqlite.

**Comment by tathougies** [comment] 2018-02-13 18:01
Ah ... this is due to the hacky way we create the postgresql-simple Query type. Unfortunately, there's no way to use its constructors, so you have to use the `IsString` instance and `BS.unpcak` is not the right function to use here. I'll get a fix for this ASAP.

**Comment by mulderr** [comment] 2018-02-13 19:10
What is the problem with `Query`? It's a [newtype over `ByteString`](https://github.com/lpsmith/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Types.hs#L80), the constructor is [exported](https://github.com/lpsmith/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Types.hs#L25).

I may be missing something here but can't we just replace `fromString (BS.unpack query)` with `Pg.Query query` or `coerce query`?

**Comment by tathougies** [comment] 2018-02-13 19:15
At some point in the past, it may not have been, or it may have been an oversight. Either way... a fix is forthcoming.

**Comment by tathougies** [comment] 2018-02-14 22:31
Do feel free to retry the queries with #142

**Comment by mulderr** [comment] 2018-02-14 23:38
Looks good on my end. @saevarb, over to you.

**Closed** 2018-02-15 06:06 UTC
Labels: bug, critical

**Comment by saevarb** [comment] 2018-02-15 15:30
I can confirm that everything seems to work on my end as well.

Thanks a lot for the swift response! I hope I'll be able to reciprocate with contributions in the future.
