### ISSUE TITLE
How to use beam-migrate-cli with nix

### ISSUE THREAD

**Issue by mckeankylej** [tathougies/beam#108] opened 2018-01-07 21:13 UTC
When attempting to use beam-migrate (the nexgen branch) with this command:
```shell
beam-migrate database add postgres Database.Beam.Postgres.Migrate <connection> --package-path /nix/store/01fsyywf1wzn2b06bmayx5zrw4749dls-beam-postgres-0.1.0.0/lib/ghc-8.0.2/package.conf.d
```
I get this error:
```shell
beam-migrate: user error (Plugin load error: UnknownError "flags: '--package-db /nix/store/01fsyywf1wzn2b06bmayx5zrw4749dls-beam-postgres-0.1.0.0/lib/ghc-8.0.2/package.conf.d' not recognized")
```
What am I doing wrong?

**Comment by tathougies** [comment] 2018-01-07 23:11
This is probably a bug due to ghc version... I’ll investigate ...

-------
Travis Athougies.

**Comment by tathougies** [comment] 2018-01-18 21:07
@mckeankylej  Which ghc version are you using, and which version of nix?

**Comment by mckeankylej** [comment] 2018-01-19 02:59
I am using ghc: `8.2.2` and nix: `18.03pre115884.b5a5d0ba84`

I made a reproducible environment to test bugs in here:

https://github.com/mckeankylej/beam-migrate-nix

If you run nix-shell in this repo it will bootstrap up to current version of nix 
(the version above). If you haven't used nix lately it will take a bit to download all the deps from the cache. This project uses the latest beam master branch. 

To execute the project:
```sh
nix-shell
cabal run -- <connection-string>
```

To launch into a shell with beam-migrate-cli:
```
./beam-migrate-env
```
Once inside `beam-migrate-env` you can try:
```
beam-migrate database add postgres Database.Beam.Postgres.Migrate <connection-string> --package-path /nix/store/qh2mz95q4dh538yd104jr18zb6cz0vkk-beam-postgres-0.2.0.0/lib/ghc-8.2.2/package.conf.d
```
When I tried that command I got:
```
beam-migrate: user error (Could not find migration registry)
```
This is a different error from the original issue. I think the error changed because I switched from `nextgen-beam-migrate` to `master`.

Anyway if you have any questions about the repro env just ask!

**Comment by tathougies** [comment] 2018-01-20 18:36
I think the flag name may have been spelled wrong. It should be fixed in latest master. I will test with your environment this afternoon

**Comment by tathougies** [comment] 2018-02-25 17:47
I finally got around to looking into this. Based on your last comment, the issue is that you need a beam-migrate registry (basically a configuration file). You should be able to get one with `beam-migrate init` in the current directory

**Closed** 2019-02-08 16:57 UTC
