### ISSUE TITLE
Conflict marker in an example

### ISSUE THREAD

**Issue by csi-adziahel** [tathougies/beam#88] opened 2017-11-28 14:24 UTC
https://github.com/tathougies/beam/blob/6681889bad98321d7f5c02c587676b540093c1c6/example/Employees.hs#L23

Not sure which is correct one

**Comment by tathougies** [comment] 2017-11-30 05:30
There is no correct one. That example is out of date. I would refer to the backend-specific examples in `beam-postgres` and `beam-sqlite` for now.

**Comment by tathougies** [comment] 2017-11-30 05:31
Duplicate of #31

**Closed by tathougies** 2017-11-30 05:31 UTC
